# Generated by Django 5.2.14 on 2026-06-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0005_rename_space_id_spacemember_space_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='space_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
