# Generated by Django 5.2.14 on 2026-06-13 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0002_alter_star_image_alter_star_space_alter_star_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='star',
            old_name='star',
            new_name='star_id',
        ),
    ]
