# Generated by Django 5.2.14 on 2026-06-13 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0003_rename_star_star_star_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='star',
            old_name='star_id',
            new_name='star',
        ),
    ]
