# Generated by Django 5.2.14 on 2026-06-13 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0004_rename_star_id_star_star'),
    ]

    operations = [
        migrations.RenameField(
            model_name='star',
            old_name='star',
            new_name='star_id',
        ),
    ]
